### ISSUE TITLE
Release Requirements

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/physionet-build#182]
- [x] Access control for files is properly implemented
- [x] DOI Assignment interface
- [ ] Determine license/dua combinations for various access policies and resource types #189 
- [x] Rigorous author contribution guidelines and project metadata fields. #185 
- [x] Unit tests
- [x] User testing
- [ ] Set up server #152
