### ISSUE TITLE
Deciding/tracking views/forms for authentication

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/physionet-build#30]
This is going to be a big issue for deciding and justifying whether to use the default Django option, or whether we should create our own custom definitions, for each authentication functionality.

The views and forms are all up for discussion, but we definitely want to define our own templates for every case. There is zero point in trying to use/adapt/extend/etc the ugly default templates when it is much less hassle to make our own.

**To decide on specific views/forms, we have to decide what pages we want.** Also, don't think about the django admin functionalities at this point. The pages we will want there will be different, and more straightforward to add in. I believe the following urls and views are appropriate (some inspiration from github settings). Note how I believe that it's cleaner/more visually usable not to provide a single page to edit one's authentication info along with their profile info. This is in contrast to what we may want in the admin page where we can edit all parts of a user/profile at once:
```
urlpatterns = [
    url(r'^login/$', views.login), # Email and password. Upon success, redirect to userhome.
    url(r'^logout/$', views.logout), # Redirect to home page of site
    url(r'^register/$', views.register), # Email, password, confirm password
    url(r'resetpassword/$', views.reset_password),
    url(r'^home/$', views.user_home), # Personalized home dashboard
    url(r'^users/(?P<email>[\w\-\.]+@[\w\-\.]+)/$', views.profile), # Public profile. No editing done here.
    url(r'settings/profile/$', views.change_profile), # edit profile info such as name, location, etc.
    url(r'settings/password/$', views.change_password),
    url(r'settings/emails/$', views.change_emails), # Each user can have multiple verified emails, one of which is primary
]
```

Tick each following item for which we should use the default django provision:
- [x] login view - Works as intended. Just have to change `settings.LOGIN_REDIRECT_URL`. Note, we use the class based view LoginView.as_view() because the view function is deprecated.
- [ ] login form - NO. The default form used for the login view is `AuthenticationForm` which does work. But I want to add some html classes to its fields to make them look better, and add a 'remember me' field. I don't think there is any harm in subclassing this form, keeping all the main functionalities and just overriding the form fields with the exact same code, plus the html attributes we want. In the form's docstring, it even does suggest subclassing it for certain cases.
- [x] logout view - YES. Works as intended. Note, we use the class based view LogoutView.as_view() because the view function is deprecated.
- [ ] register view -NO. There is no django default for this.
- [ ] register form - NO. There is a usercreationform but we'd end up overriding 95% of it anyway.
- [x] password reset view - YES. Works as intended.
- [x] password reset form - YES. Works as intended.
- [ ] profile edit view - NO. There is no django default for this.
- [ ] profile edit form - NO. There is no django default for this.
- [x] password edit view - YES. Works as intended. I commented earlier about a weird popup box. That was from firefox password manager. Annoyingly though, it forces a success redirect url. If I set it to the same page, I can't show a 'success' alert since I can't control the view.
- [x] password edit form - YES. Works as intended.
- [ ] emails edit view - NO. There is no django default for this.
- [ ] emails edit form - NO. There is no django default for this.

Possible reasons for needing custom definitions:
- The default view contains unwanted logic such as unwanted redirects.
- The default views are trying to access certain model fields which we have overwritten, and cannot be stopped from doing so.

For everyone's information, here is the django auth urls file so you can see what views they do have:
```
urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),

    url(r'^password_change/$', views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change/done/$', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
```

Reference: https://docs.djangoproject.com/en/1.11/topics/auth/default/
